name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    env:
      TERM: 'dumb'
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Install uv and Python
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Setup uv venv
      run: uv sync --locked --all-extras --dev

    - name: Lint with ruff
      run: uv run ruff check streaq/ tests/ example.py

    - name: Type check with pyright
      run: uv run pyright streaq/ tests/ example.py

    - name: Test with pytest
      run: |
        docker compose run --rm tests uv run --locked --all-extras --dev pytest -n auto --dist=loadgroup --cov=streaq tests/

    - name: Generate coverage badge
      if: matrix.python-version == '3.13' && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: tj-actions/coverage-badge-py@v2

    - name: Verify changed files
      if: matrix.python-version == '3.13' && github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: tj-actions/verify-changed-files@v20
      id: verify-changed-files
      with:
        files: coverage.svg

    - name: Commit files
      if: matrix.python-version == '3.13' && github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add coverage.svg
        git commit -m "Update badge"

    - name: Push changes
      if: matrix.python-version == '3.13' && github.event_name == 'push' && github.ref == 'refs/heads/master' && steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: badges
        force: true
